In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("retail_sales_practice.csv")
df.head()

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Sales,Discount,Profit
0,1000,2024-09-07,CUST915,Mumbai,Tablet,Electronics,3,7960.0,5.0,2567.753004
1,1001,2024-06-24,CUST661,DELHI,Tablet,Electronics,4,2939.0,15.0,940.113048
2,1002,2024-11-11,CUST664,Chennai,Phone,Electronics,2,8117.0,10.0,8654.882097
3,1003,2024-12-21,CUST844,Mumbai,Laptop,NaN,4,6290.0,5.0,3511.883308
4,1004,2024-12-16,CUST764,Dehli,Printer,Electronics,4,6413.0,5.0,2760.942508

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     505 non-null    int64
 1   Order_Date   505 non-null    object
 2   Customer_ID  505 non-null    object
 3   City         505 non-null    object
 4   Product      505 non-null    object
 5   Category     342 non-null    object
 6   Quantity     505 non-null    int64
 7   Sales        504 non-null    float64
 8   Discount     407 non-null    float64
 9   Profit       505 non-null    float64
dtypes: float64(3), int64(2), object(5)
memory usage: 39.6+ KB

In [ ]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [ ]:
df = df.dropna(subset=['Sales'])

In [ ]:
df['Category'] = df['Category'].fillna("Unknown")

In [ ]:
df['Discount'] = df['Discount'].fillna(0)

In [ ]:
df[(df['Quantity'] == 0) & (df['Sales'] > 0)].shape[0]

90

In [ ]:
df[df['Quantity'] == 0]['Product'].value_counts()

Product
Phone      26
Tablet     26
Printer    23
Laptop     15
Name: count, dtype: int64

In [ ]:
df = df[~((df['Quantity'] == 0) & (df['Sales'] > 0))]

In [ ]:
df[df['Profit'] > df['Sales']].shape[0]

62

In [ ]:
df[df['Profit'] > df['Sales']].head()

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Sales,Discount,Profit
2,1002,2024-11-11,CUST664,Chennai,Phone,Electronics,2,8117.0,10.0,8654.882097
10,1010,2024-09-12,CUST244,Delhi,Laptop,Electronics,3,2660.0,0.0,3034.716482
20,1020,2024-04-12,CUST996,DELHI,Laptop,Electronics,4,5660.0,5.0,5908.183100
24,1024,2024-08-04,CUST657,Kolkata,Laptop,Electronics,5,8791.0,0.0,10414.670689
49,1049,2024-11-01,CUST971,Delhi,Tablet,Unknown,3,7345.0,15.0,8305.672827

In [ ]:
df = df[df['Profit'] <= df['Sales']]

In [ ]:
df.shape

(352, 10)

In [ ]:
df.isnull().sum()

Order_ID       0
Order_Date     0
Customer_ID    0
City           0
Product        0
Category       0
Quantity       0
Sales          0
Discount       0
Profit         0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.shape

(348, 10)

In [ ]:
df.dtypes

Order_ID                int64
Order_Date     datetime64[ns]
Customer_ID            object
City                   object
Product                object
Category               object
Quantity                int64
Sales                 float64
Discount              float64
Profit                float64
dtype: object

In [ ]:
df[df['Quantity'] <= 0]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, City, Product, Category, Quantity, Sales, Discount, Profit]
Index: []

In [ ]:
df[(df['Discount'] < 0) | (df['Discount'] > 1)]

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Sales,Discount,Profit
0,1000,2024-09-07,CUST915,Mumbai,Tablet,Electronics,3,7960.0,5.0,2567.753004
1,1001,2024-06-24,CUST661,DELHI,Tablet,Electronics,4,2939.0,15.0,940.113048
3,1003,2024-12-21,CUST844,Mumbai,Laptop,Unknown,4,6290.0,5.0,3511.883308
4,1004,2024-12-16,CUST764,Dehli,Printer,Electronics,4,6413.0,5.0,2760.942508
6,1006,2024-12-21,CUST303,Mumbai,Printer,Electronics,2,3744.0,15.0,3069.327313
...,...,...,...,...,...,...,...,...,...,...
493,1493,2024-05-30,CUST631,Dehli,Laptop,Electronics,3,4829.0,5.0,3446.692476
495,1495,2024-11-01,CUST872,Delhi,Tablet,Electronics,3,5660.0,15.0,3106.607534
497,1497,2024-03-30,CUST440,DELHI,Laptop,Unknown,1,1162.0,10.0,803.811959
498,1498,2024-11-11,CUST126,DELHI,Laptop,Electronics,4,4532.0,10.0,4457.290204
499,1499,2024-10-31,CUST269,Delhi,Laptop,Electronics,3,9640.0,15.0,8704.619914

In [ ]:
df['Discount'] = df['Discount'] / 100

In [ ]:
df['Discount'].describe()

count    348.000000
mean       0.062213
std        0.059793
min        0.000000
25%        0.000000
50%        0.050000
75%        0.100000
max        0.150000
Name: Discount, dtype: float64

In [ ]:
df['City'] = df['City'].str.strip()        # remove spaces
df['City'] = df['City'].str.title()        # make proper case
df['City'] = df['City'].replace('Dehli', 'Delhi')  # fix typo

In [ ]:
df['City'].unique()

array(['Mumbai', 'Delhi', 'Kolkata', 'Chennai'], dtype=object)

In [ ]:
df['Category'].unique()

array(['Electronics', 'Unknown'], dtype=object)

In [ ]:
df[df['Category'] == 'Unknown'].shape

(120, 10)

In [ ]:
df['Category'] = df['Category'].replace('Unknown', 'Others')

In [ ]:
df['Category'].value_counts()

Category
Electronics    228
Others         120
Name: count, dtype: int64

In [ ]:
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month
df['Profit_Margin'] = df['Profit'] / df['Sales']

In [ ]:
df.head()

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Sales,Discount,Profit,Year,Month,Profit_Margin
0,1000,2024-09-07,CUST915,Mumbai,Tablet,Electronics,3,7960.0,0.05,2567.753004,2024,9,0.322582
1,1001,2024-06-24,CUST661,Delhi,Tablet,Electronics,4,2939.0,0.15,940.113048,2024,6,0.319875
3,1003,2024-12-21,CUST844,Mumbai,Laptop,Others,4,6290.0,0.05,3511.883308,2024,12,0.558328
4,1004,2024-12-16,CUST764,Delhi,Printer,Electronics,4,6413.0,0.05,2760.942508,2024,12,0.430523
5,1005,2024-04-21,CUST671,Delhi,Laptop,Electronics,1,2690.0,0.00,1522.793425,2024,4,0.566094

In [ ]:
df['Profit_Margin'].describe()

count    348.000000
mean       0.540047
std        0.267765
min        0.050382
25%        0.314395
50%        0.541547
75%        0.764852
max        0.999079
Name: Profit_Margin, dtype: float64

In [ ]:
df[df['Profit_Margin'] > 0.9]

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Sales,Discount,Profit,Year,Month,Profit_Margin
17,1017,2024-06-08,CUST225,Delhi,Tablet,Electronics,5,3679.0,0.00,3491.587617,2024,6,0.949059
65,1065,2024-06-25,CUST164,Kolkata,Phone,Electronics,3,7814.0,0.00,7296.691862,2024,6,0.933797
67,1067,2024-02-17,CUST744,Delhi,Tablet,Electronics,3,3684.0,0.05,3554.459241,2024,2,0.964837
80,1080,2024-02-03,CUST973,Delhi,Printer,Electronics,1,6901.0,0.10,6316.429588,2024,2,0.915292
85,1085,2024-11-28,CUST520,Mumbai,Laptop,Electronics,3,3277.0,0.15,3047.510033,2024,11,0.929969
114,1114,2024-12-31,CUST187,Delhi,Laptop,Electronics,1,4920.0,0.10,4850.289659,2024,12,0.985831
122,1122,2024-03-27,CUST898,Chennai,Printer,Electronics,5,2781.0,0.05,2527.670572,2024,3,0.908907
125,1125,2024-01-03,CUST481,Delhi,Laptop,Others,3,5586.0,0.00,5562.273083,2024,1,0.995752
146,1146,2024-09-24,CUST201,Delhi,Printer,Electronics,3,5669.0,0.05,5650.009519,2024,9,0.996650
150,1150,2024-01-23,CUST421,Mumbai,Printer,Electronics,4,828.0,0.00,802.951559,2024,1,0.969748
153,1153,2024-01-07,CUST239,Delhi,Laptop,Others,4,6471.0,0.00,6227.809123,2024,1,0.962418
158,1158,2024-06-21,CUST891,Delhi,Printer,Electronics,5,7594.0,0.10,7503.714479,2024,6,0.988111
166,1166,2024-04-10,CUST259,Kolkata,Phone,Electronics,5,4179.0,0.00,4023.563883,2024,4,0.962805
171,1171,2024-02-21,CUST792,Delhi,Laptop,Others,3,7748.0,0.00,7247.761268,2024,2,0.935436
178,1178,2024-05-10,CUST452,Delhi,Tablet,Others,5,9187.0,0.10,9012.074670,2024,5,0.980959
208,1208,2024-02-29,CUST747,Chennai,Printer,Electronics,5,5448.0,0.05,5113.035912,2024,2,0.938516
237,1237,2024-04-13,CUST422,Mumbai,Tablet,Electronics,3,951.0,0.00,873.078382,2024,4,0.918063
241,1241,2024-06-10,CUST232,Delhi,Phone,Electronics,2,6606.0,0.10,6573.481374,2024,6,0.995077
251,1251,2024-11-17,CUST213,Delhi,Printer,Electronics,2,860.0,0.10,803.145207,2024,11,0.933890
256,1256,2024-05-03,CUST751,Chennai,Phone,Others,2,828.0,0.05,791.640273,2024,5,0.956087
269,1269,2024-06-03,CUST711,Delhi,Tablet,Others,1,3630.0,0.00,3626.656859,2024,6,0.999079
274,1274,2024-06-19,CUST550,Delhi,Laptop,Electronics,3,7005.0,0.00,6684.292539,2024,6,0.954217
287,1287,2024-06-01,CUST478,Delhi,Printer,Others,2,1115.0,0.10,1105.572959,2024,6,0.991545
304,1304,2024-11-03,CUST809,Delhi,Printer,Electronics,4,2126.0,0.00,2123.833356,2024,11,0.998981
311,1311,2024-02-17,CUST730,Mumbai,Phone,Electronics,4,4264.0,0.00,4021.941994,2024,2,0.943232
327,1327,2024-10-20,CUST663,Kolkata,Printer,Electronics,5,7286.0,0.15,6684.115023,2024,10,0.917392
333,1333,2024-04-26,CUST806,Delhi,Laptop,Others,2,9307.0,0.00,8842.584859,2024,4,0.950100
346,1346,2024-03-27,CUST787,Delhi,Tablet,Electronics,2,6268.0,0.15,6022.969331,2024,3,0.960908
358,1358,2024-04-15,CUST883,Delhi,Laptop,Others,2,2639.0,0.00,2530.506478,2024,4,0.958888
379,1379,2024-02-27,CUST970,Delhi,Tablet,Electronics,2,7646.0,0.00,7510.580296,2024,2,0.982289
393,1393,2024-12-21,CUST723,Delhi,Laptop,Others,4,9917.0,0.10,9404.747157,2024,12,0.948346
394,1394,2024-05-01,CUST301,Delhi,Tablet,Electronics,1,5911.0,0.00,5904.509872,2024,5,0.998902
407,1407,2024-08-14,CUST982,Chennai,Printer,Electronics,5,6476.0,0.05,5881.103929,2024,8,0.908138
409,1409,2024-05-20,CUST399,Mumbai,Phone,Electronics,3,5832.0,0.10,5671.329227,2024,5,0.972450
418,1418,2024-04-19,CUST210,Delhi,Phone,Others,5,3679.0,0.15,3500.270789,2024,4,0.951419
428,1428,2024-11-26,CUST301,Delhi,Printer,Electronics,5,4074.0,0.05,3869.720120,2024,11,0.949858
475,1475,2024-12-22,CUST754,Delhi,Phone,Electronics,4,4334.0,0.00,3970.661001,2024,12,0.916165
487,1487,2024-09-18,CUST834,Delhi,Tablet,Electronics,3,5152.0,0.00,4749.694554,2024,9,0.921913
488,1488,2024-08-04,CUST572,Delhi,Laptop,Electronics,4,2182.0,0.05,1974.573306,2024,8,0.904937
498,1498,2024-11-11,CUST126,Delhi,Laptop,Electronics,4,4532.0,0.10,4457.290204,2024,11,0.983515
499,1499,2024-10-31,CUST269,Delhi,Laptop,Electronics,3,9640.0,0.15,8704.619914,2024,10,0.902969

In [ ]:
df.to_csv("cleaned_retail_sales.csv", index=False)

In [ ]:
import os
os.listdir()

['.config',
 'retail_sales_practice.csv',
 'cleaned_retail_sales.csv',
 'sample_data']